# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba318d182c852b85e963835a777a2dfb"
name = "ubeauty-tbyb-app-v2"
handle = "ubeauty-tbyb-app-v2"
application_url = "https://chemicals-nathan-ricky-orleans.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/create" ]
  uri = "/webhooks/subscription_contracts/create"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_cycles/skip" ]
  uri = "/webhooks/subscription_billing_cycles/skip"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_fulfillments,read_orders,read_payment_terms,read_products,read_purchase_options,write_customers,write_draft_orders,write_fulfillments,write_orders,write_payment_terms,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://chemicals-nathan-ricky-orleans.trycloudflare.com/auth/callback",
  "https://chemicals-nathan-ricky-orleans.trycloudflare.com/auth/shopify/callback",
  "https://chemicals-nathan-ricky-orleans.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "Try Before You Buy Extension"
handle = "tbyb"
